org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.parallel=true
org.gradle.caching=true

# Forge 1.20.1 line
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.10
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1

## Mod Properties
mod_id=stardewcraft
mod_name=Starfield Pastoral
mod_license=Custom Lisence
mod_version=0.6.2-forge.0
mod_group_id=com.stardew.craft
mod_authors=Elysium
mod_description=StardewCraft Forge 1.20.1 migration bootstrap.
