package com.stardew.craft.port;

import java.util.List;

/**
 * GENERATED by scripts/port/gen_enchantment_rules_1201.py from minecraft_1.21.1_client.jar - do not edit.
 * <p>
 * PORT(1.20.1): the 1.21.1 vanilla enchantment definitions' applicability fields, verbatim HolderSet strings
 * ({@code "#tag"} or {@code "id"}): {@code supported_items} (anvil, {@code /enchant}, {@code enchant_randomly}),
 * {@code primary_items} (enchanting table / {@code enchant_with_levels}; {@code null} = supported items) and
 * {@code exclusive_set}. Only enchantments that exist in 1.20.1 are listed ({@code id} is the 1.20.1 id);
 * not in 1.20.1: minecraft:breach, minecraft:density, minecraft:wind_burst.
 * Applied to StardewCraft items by {@link PortVanillaEnchantmentRules}.
 */
final class PortVanillaEnchantmentTable {
    record Entry(String id1211, String id, String supportedItems, String primaryItems, String exclusiveSet) {}

    static final List<Entry> ENTRIES = List.of(
            new Entry("minecraft:aqua_affinity", "minecraft:aqua_affinity", "#minecraft:enchantable/head_armor", null, null),
            new Entry("minecraft:bane_of_arthropods", "minecraft:bane_of_arthropods", "#minecraft:enchantable/weapon", "#minecraft:enchantable/sword", "#minecraft:exclusive_set/damage"),
            new Entry("minecraft:binding_curse", "minecraft:binding_curse", "#minecraft:enchantable/equippable", null, null),
            new Entry("minecraft:blast_protection", "minecraft:blast_protection", "#minecraft:enchantable/armor", null, "#minecraft:exclusive_set/armor"),
            new Entry("minecraft:channeling", "minecraft:channeling", "#minecraft:enchantable/trident", null, null),
            new Entry("minecraft:depth_strider", "minecraft:depth_strider", "#minecraft:enchantable/foot_armor", null, "#minecraft:exclusive_set/boots"),
            new Entry("minecraft:efficiency", "minecraft:efficiency", "#minecraft:enchantable/mining", null, null),
            new Entry("minecraft:feather_falling", "minecraft:feather_falling", "#minecraft:enchantable/foot_armor", null, null),
            new Entry("minecraft:fire_aspect", "minecraft:fire_aspect", "#minecraft:enchantable/fire_aspect", "#minecraft:enchantable/sword", null),
            new Entry("minecraft:fire_protection", "minecraft:fire_protection", "#minecraft:enchantable/armor", null, "#minecraft:exclusive_set/armor"),
            new Entry("minecraft:flame", "minecraft:flame", "#minecraft:enchantable/bow", null, null),
            new Entry("minecraft:fortune", "minecraft:fortune", "#minecraft:enchantable/mining_loot", null, "#minecraft:exclusive_set/mining"),
            new Entry("minecraft:frost_walker", "minecraft:frost_walker", "#minecraft:enchantable/foot_armor", null, "#minecraft:exclusive_set/boots"),
            new Entry("minecraft:impaling", "minecraft:impaling", "#minecraft:enchantable/trident", null, "#minecraft:exclusive_set/damage"),
            new Entry("minecraft:infinity", "minecraft:infinity", "#minecraft:enchantable/bow", null, "#minecraft:exclusive_set/bow"),
            new Entry("minecraft:knockback", "minecraft:knockback", "#minecraft:enchantable/sword", null, null),
            new Entry("minecraft:looting", "minecraft:looting", "#minecraft:enchantable/sword", null, null),
            new Entry("minecraft:loyalty", "minecraft:loyalty", "#minecraft:enchantable/trident", null, null),
            new Entry("minecraft:luck_of_the_sea", "minecraft:luck_of_the_sea", "#minecraft:enchantable/fishing", null, null),
            new Entry("minecraft:lure", "minecraft:lure", "#minecraft:enchantable/fishing", null, null),
            new Entry("minecraft:mending", "minecraft:mending", "#minecraft:enchantable/durability", null, null),
            new Entry("minecraft:multishot", "minecraft:multishot", "#minecraft:enchantable/crossbow", null, "#minecraft:exclusive_set/crossbow"),
            new Entry("minecraft:piercing", "minecraft:piercing", "#minecraft:enchantable/crossbow", null, "#minecraft:exclusive_set/crossbow"),
            new Entry("minecraft:power", "minecraft:power", "#minecraft:enchantable/bow", null, null),
            new Entry("minecraft:projectile_protection", "minecraft:projectile_protection", "#minecraft:enchantable/armor", null, "#minecraft:exclusive_set/armor"),
            new Entry("minecraft:protection", "minecraft:protection", "#minecraft:enchantable/armor", null, "#minecraft:exclusive_set/armor"),
            new Entry("minecraft:punch", "minecraft:punch", "#minecraft:enchantable/bow", null, null),
            new Entry("minecraft:quick_charge", "minecraft:quick_charge", "#minecraft:enchantable/crossbow", null, null),
            new Entry("minecraft:respiration", "minecraft:respiration", "#minecraft:enchantable/head_armor", null, null),
            new Entry("minecraft:riptide", "minecraft:riptide", "#minecraft:enchantable/trident", null, "#minecraft:exclusive_set/riptide"),
            new Entry("minecraft:sharpness", "minecraft:sharpness", "#minecraft:enchantable/sharp_weapon", "#minecraft:enchantable/sword", "#minecraft:exclusive_set/damage"),
            new Entry("minecraft:silk_touch", "minecraft:silk_touch", "#minecraft:enchantable/mining_loot", null, "#minecraft:exclusive_set/mining"),
            new Entry("minecraft:smite", "minecraft:smite", "#minecraft:enchantable/weapon", "#minecraft:enchantable/sword", "#minecraft:exclusive_set/damage"),
            new Entry("minecraft:soul_speed", "minecraft:soul_speed", "#minecraft:enchantable/foot_armor", null, null),
            new Entry("minecraft:sweeping_edge", "minecraft:sweeping", "#minecraft:enchantable/sword", null, null),
            new Entry("minecraft:swift_sneak", "minecraft:swift_sneak", "#minecraft:enchantable/leg_armor", null, null),
            new Entry("minecraft:thorns", "minecraft:thorns", "#minecraft:enchantable/armor", "#minecraft:enchantable/chest_armor", null),
            new Entry("minecraft:unbreaking", "minecraft:unbreaking", "#minecraft:enchantable/durability", null, null),
            new Entry("minecraft:vanishing_curse", "minecraft:vanishing_curse", "#minecraft:enchantable/vanishing", null, null));

    private PortVanillaEnchantmentTable() {}
}
