package com.stardew.craft.server.performance;

public enum PerformanceTiming {
    SERVER_TICK,
    PLAYER_LOGIN_EVENT,
    NPC_TICK,
    FESTIVAL_TICK,
    FISHING_TICK,
    CUTSCENE_TRIGGER_SCAN,
    CONTENT_SYNC,
    CONTENT_SNAPSHOT_BUILD,
    JEI_CATALOG_BUILD,
    FARM_SYNC_CHUNK_LOAD,
    DAILY_SYNC_CHUNK_LOAD,
    FARM_DAILY_PROCESS,
    OFFLINE_FARM_CATCH_UP
}
