param(
    [Parameter(Mandatory = $true)]
    [string]$SourceRegionDir,

    [switch]$CleanTarget,

    [int]$PregenVersion = 19
)

$ErrorActionPreference = 'Stop'

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$repoRoot = Split-Path -Parent $scriptDir

$targetRoot = Join-Path $repoRoot 'src\main\resources\pregen\stardew_valley'
$targetRegionDir = Join-Path $targetRoot 'region'
$manifestPath = Join-Path $targetRoot 'region_manifest.txt'
$farmRegionStart = 20001
$protectedPlayerRegionMin = 36

function Test-ProtectedRegionFile {
    param([string]$Name)

    if ($Name -notmatch '^r\.(-?\d+)\.(-?\d+)\.mca$') {
        return $true
    }
    $regionX = [int]$Matches[1]
    $regionZ = [int]$Matches[2]
    $maxBlockX = (($regionX + 1) * 512) - 1
    $maxBlockZ = (($regionZ + 1) * 512) - 1
    $farmRegion = $maxBlockX -ge $farmRegionStart -and $maxBlockZ -ge $farmRegionStart
    $dynamicInteriorRegion = $regionX -ge $protectedPlayerRegionMin -and $regionZ -ge $protectedPlayerRegionMin
    return $farmRegion -or $dynamicInteriorRegion
}

if (-not (Test-Path -Path $SourceRegionDir -PathType Container)) {
    throw "SourceRegionDir does not exist: $SourceRegionDir"
}

New-Item -ItemType Directory -Path $targetRegionDir -Force | Out-Null

if ($CleanTarget) {
    Get-ChildItem -Path $targetRegionDir -Filter '*.mca' -File -ErrorAction SilentlyContinue |
        Remove-Item -Force
}

$sourceFiles = Get-ChildItem -Path $SourceRegionDir -Filter '*.mca' -File |
    Where-Object { -not (Test-ProtectedRegionFile $_.Name) } |
    Sort-Object Name

if ($sourceFiles.Count -eq 0) {
    throw "No .mca files found in: $SourceRegionDir"
}

foreach ($file in $sourceFiles) {
    Copy-Item -Path $file.FullName -Destination (Join-Path $targetRegionDir $file.Name) -Force
}

$targetFiles = Get-ChildItem -Path $targetRegionDir -Filter '*.mca' -File |
    Where-Object { -not (Test-ProtectedRegionFile $_.Name) } |
    Sort-Object Name

$manifestLines = @(
    '# Auto-generated by scripts/setup_valley_pregen.ps1',
    "# pregen-version $PregenVersion",
    '# copy <filename> <size> <sha256> | delete <filename>'
)
foreach ($file in $targetFiles) {
    if ($file.Length -eq 0) {
        $manifestLines += "delete $($file.Name)"
    }
    else {
        $sha256 = (Get-FileHash -Path $file.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
        $manifestLines += "copy $($file.Name) $($file.Length) $sha256"
    }
}

$utf8NoBom = New-Object System.Text.UTF8Encoding($false)
[System.IO.File]::WriteAllLines($manifestPath, $manifestLines, $utf8NoBom)

Write-Host "[VALLEY_PREGEN] Source: $SourceRegionDir"
Write-Host "[VALLEY_PREGEN] Copied: $($sourceFiles.Count) files"
Write-Host "[VALLEY_PREGEN] Target: $targetRegionDir"
Write-Host "[VALLEY_PREGEN] Manifest: $manifestPath"
