package com.stardew.craft.gametest;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.stardew.craft.StardewCraft;
import com.stardew.craft.port.PortGameTests;
import com.stardew.craft.port.PortVanillaEnchantmentRules;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeSet;
import net.minecraft.core.BlockPos;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.gametest.framework.GameTest;
import net.minecraft.gametest.framework.GameTestHelper;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.MinecraftServer;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.EquipmentSlot;
import net.minecraft.world.entity.decoration.ArmorStand;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.inventory.AnvilMenu;
import net.minecraft.world.item.EnchantedBookItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.EnchantmentHelper;
import net.minecraft.world.item.enchantment.EnchantmentInstance;
import net.minecraft.world.level.GameType;
import net.minecraftforge.gametest.GameTestHolder;
import net.minecraftforge.gametest.PrefixGameTestTemplate;

/**
 * Port verification only (never shipped from main): the 1.20.1 runtime decisions about vanilla enchantments on
 * StardewCraft items must equal the 1.21.1 results in {@code port-parity/enchantment_rules_expected_1211.json}
 * (generated by {@code scripts/port/gen_enchantment_rules_1201.py} from the 1.21.1 vanilla jar and the mod's 1.21.1
 * tag files, cross-checked against the 1.21.1 content dump). Covers {@code Enchantment#canEnchant} (1.21
 * {@code supportsEnchantment}), {@code canApplyAtEnchantingTable} (1.21 {@code isPrimaryItemFor}), the enchanting
 * table's candidate list, the exclusive-set compatibility used for StardewCraft items, and end-to-end anvil and
 * {@code /enchant} cases.
 */
@GameTestHolder(StardewCraft.MODID)
@PrefixGameTestTemplate(false)
public final class PortEnchantmentParityGameTests {
    private static final String NS = StardewCraft.MODID;
    private static final String EXPECTED = "/port-parity/enchantment_rules_expected_1211.json";
    private static final int MAX_REPORTED = 25;

    private record Expected(Map<Enchantment, Set<String>> supported, Map<Enchantment, Set<String>> primary,
                            Set<Enchantment> inEnchantingTable, Set<List<Enchantment>> incompatible) {}

    private static Expected load() throws Exception {
        try (InputStream in = PortEnchantmentParityGameTests.class.getResourceAsStream(EXPECTED)) {
            if (in == null) throw new IllegalStateException("missing " + EXPECTED);
            JsonObject root = JsonParser.parseReader(new InputStreamReader(in, StandardCharsets.UTF_8)).getAsJsonObject();
            Map<Enchantment, Set<String>> supported = new LinkedHashMap<>();
            Map<Enchantment, Set<String>> primary = new LinkedHashMap<>();
            Set<Enchantment> table = new HashSet<>();
            for (Map.Entry<String, JsonElement> e : root.getAsJsonObject("enchantments").entrySet()) {
                Enchantment enchantment = enchantment(e.getKey());
                JsonObject o = e.getValue().getAsJsonObject();
                supported.put(enchantment, strings(o.getAsJsonArray("supported")));
                primary.put(enchantment, strings(o.getAsJsonArray("primary")));
                if (o.get("in_enchanting_table").getAsBoolean()) table.add(enchantment);
            }
            Set<List<Enchantment>> incompatible = new HashSet<>();
            for (JsonElement pair : root.getAsJsonArray("incompatible")) {
                Enchantment a = enchantment(pair.getAsJsonArray().get(0).getAsString());
                Enchantment b = enchantment(pair.getAsJsonArray().get(1).getAsString());
                incompatible.add(List.of(a, b));
                incompatible.add(List.of(b, a));
            }
            return new Expected(supported, primary, table, incompatible);
        }
    }

    private static Set<String> strings(JsonArray array) {
        Set<String> out = new TreeSet<>();
        array.forEach(e -> out.add(e.getAsString()));
        return out;
    }

    private static Enchantment enchantment(String id) {
        Enchantment enchantment = BuiltInRegistries.ENCHANTMENT.get(new ResourceLocation(id));
        if (enchantment == null) throw new IllegalStateException("unknown enchantment " + id);
        return enchantment;
    }

    private static Item item(String id) {
        ResourceLocation key = new ResourceLocation(id);
        if (!BuiltInRegistries.ITEM.containsKey(key)) throw new IllegalStateException("unknown item " + id);
        return BuiltInRegistries.ITEM.get(key);
    }

    private static List<Item> modItems() {
        List<Item> items = new ArrayList<>();
        for (Item item : BuiltInRegistries.ITEM) {
            if (BuiltInRegistries.ITEM.getKey(item).getNamespace().equals(NS)) items.add(item);
        }
        return items;
    }

    private static void report(GameTestHelper helper, String what, List<String> mismatches) {
        if (mismatches.isEmpty()) return;
        helper.fail(what + ": " + mismatches.size() + " mismatch(es) vs 1.21.1, e.g. "
                + mismatches.subList(0, Math.min(MAX_REPORTED, mismatches.size())));
    }

    /** {@code canEnchant} / {@code canApplyAtEnchantingTable} for every StardewCraft item x ported vanilla enchantment. */
    @GameTest(templateNamespace = "stardewcraft_port_dump", template = "empty")
    public static void vanillaEnchantmentApplicabilityMatches1211(GameTestHelper helper) throws Exception {
        Expected expected = load();
        Set<String> registered = new HashSet<>();
        List<String> mismatches = new ArrayList<>();
        for (Item item : modItems()) {
            String id = BuiltInRegistries.ITEM.getKey(item).toString();
            registered.add(id);
            ItemStack stack = new ItemStack(item);
            for (Enchantment enchantment : expected.supported().keySet()) {
                String ench = BuiltInRegistries.ENCHANTMENT.getKey(enchantment).toString();
                boolean supported = expected.supported().get(enchantment).contains(id);
                boolean primary = expected.primary().get(enchantment).contains(id);
                if (enchantment.canEnchant(stack) != supported) {
                    mismatches.add(id + " canEnchant " + ench + " expected " + supported);
                }
                if (enchantment.canApplyAtEnchantingTable(stack) != primary) {
                    mismatches.add(id + " canApplyAtEnchantingTable " + ench + " expected " + primary);
                }
            }
        }
        for (Set<String> ids : expected.supported().values()) {
            for (String id : ids) {
                if (!registered.contains(id)) mismatches.add(id + " is enchantable in 1.21.1 but not registered");
            }
        }
        report(helper, "vanilla enchantment applicability", mismatches);
        helper.succeed();
    }

    /** The enchanting table offers a StardewCraft item exactly its 1.21.1 primary, in-table vanilla enchantments. */
    @GameTest(templateNamespace = "stardewcraft_port_dump", template = "empty")
    public static void enchantingTableCandidatesMatch1211(GameTestHelper helper) throws Exception {
        Expected expected = load();
        List<String> mismatches = new ArrayList<>();
        for (Item item : modItems()) {
            String id = BuiltInRegistries.ITEM.getKey(item).toString();
            ItemStack stack = new ItemStack(item);
            Set<String> offered = new TreeSet<>();
            for (int level = 1; level <= 100; level++) {
                for (EnchantmentInstance instance : EnchantmentHelper.getAvailableEnchantmentResults(level, stack, false)) {
                    if (expected.supported().containsKey(instance.enchantment)) {
                        offered.add(BuiltInRegistries.ENCHANTMENT.getKey(instance.enchantment).toString());
                    }
                }
            }
            Set<String> wanted = new TreeSet<>();
            for (Enchantment enchantment : expected.primary().keySet()) {
                if (expected.inEnchantingTable().contains(enchantment) && expected.primary().get(enchantment).contains(id)) {
                    wanted.add(BuiltInRegistries.ENCHANTMENT.getKey(enchantment).toString());
                }
            }
            if (!offered.equals(wanted)) mismatches.add(id + " offers " + offered + " expected " + wanted);
        }
        report(helper, "enchanting table candidates", mismatches);
        helper.succeed();
    }

    /** Exclusive-set compatibility applied to StardewCraft items equals 1.21.1 {@code Enchantment.areCompatible}. */
    @GameTest(templateNamespace = "stardewcraft_port_dump", template = "empty")
    public static void vanillaEnchantmentCompatibilityMatches1211(GameTestHelper helper) throws Exception {
        Expected expected = load();
        ItemStack target = new ItemStack(item(NS + ":rusty_sword"));
        List<String> mismatches = new ArrayList<>();
        for (Enchantment a : expected.supported().keySet()) {
            for (Enchantment b : expected.supported().keySet()) {
                if (a == b) continue;
                boolean wanted = !expected.incompatible().contains(List.of(a, b));
                if (PortVanillaEnchantmentRules.areCompatible(target, a, b) != wanted) {
                    mismatches.add(BuiltInRegistries.ENCHANTMENT.getKey(a) + " + " + BuiltInRegistries.ENCHANTMENT.getKey(b)
                            + " expected " + (wanted ? "compatible" : "incompatible"));
                }
            }
        }
        report(helper, "vanilla enchantment compatibility", mismatches);
        helper.succeed();
    }

    private static ItemStack anvil(Player player, ItemStack left, Enchantment book) {
        AnvilMenu menu = new AnvilMenu(0, player.getInventory());
        menu.getSlot(AnvilMenu.INPUT_SLOT).set(left);
        menu.getSlot(AnvilMenu.ADDITIONAL_SLOT).set(EnchantedBookItem.createForEnchantment(new EnchantmentInstance(book, 1)));
        menu.createResult();
        return menu.getSlot(AnvilMenu.RESULT_SLOT).getItem();
    }

    private static ItemStack enchanted(Item item, Enchantment enchantment) {
        ItemStack stack = new ItemStack(item);
        stack.enchant(enchantment, 1);
        return stack;
    }

    private static void expectAnvil(GameTestHelper helper, Player player, ItemStack left, Enchantment book,
                                    boolean applied, List<String> failures) {
        List<String> existing = EnchantmentHelper.getEnchantments(left).keySet().stream()
                .map(e -> String.valueOf(BuiltInRegistries.ENCHANTMENT.getKey(e))).toList();
        String label = BuiltInRegistries.ITEM.getKey(left.getItem()) + existing.toString()
                + " + book " + BuiltInRegistries.ENCHANTMENT.getKey(book);
        ItemStack result = anvil(player, left.copy(), book);
        boolean got = !result.isEmpty() && EnchantmentHelper.getEnchantments(result).containsKey(book);
        if (got != applied) failures.add(label + (applied ? " should apply" : " should not apply"));
    }

    /** End-to-end anvil: 1.21.1 applicability and exclusive sets for StardewCraft items, vanilla items untouched. */
    @GameTest(templateNamespace = "stardewcraft_port_dump", template = "empty")
    public static void anvilUses1211RulesForStardewItems(GameTestHelper helper) {
        List<String> failures = new ArrayList<>();
        Player survival = PortGameTests.makeMockPlayer(helper, GameType.SURVIVAL);
        Enchantment efficiency = enchantment("minecraft:efficiency");
        Enchantment sharpness = enchantment("minecraft:sharpness");
        Enchantment unbreaking = enchantment("minecraft:unbreaking");
        Enchantment lure = enchantment("minecraft:lure");
        Enchantment looting = enchantment("minecraft:looting");
        Enchantment silkTouch = enchantment("minecraft:silk_touch");
        Enchantment impaling = enchantment("minecraft:impaling");
        // 1.21.1: #minecraft:hoes -> enchantable/mining, mining_loot, durability (no sharp_weapon).
        expectAnvil(helper, survival, new ItemStack(item(NS + ":hoe")), efficiency, true, failures);
        expectAnvil(helper, survival, new ItemStack(item(NS + ":hoe")), unbreaking, true, failures);
        expectAnvil(helper, survival, new ItemStack(item(NS + ":hoe")), sharpness, false, failures);
        // Axes: Sharpness is supported (sharp_weapon) although not primary (sword).
        expectAnvil(helper, survival, new ItemStack(item(NS + ":axe")), sharpness, true, failures);
        // Not in any vanilla enchantable tag in 1.21.1.
        expectAnvil(helper, survival, new ItemStack(item(NS + ":fishing_rod")), lure, false, failures);
        expectAnvil(helper, survival, new ItemStack(item(NS + ":scythe")), efficiency, false, failures);
        expectAnvil(helper, survival, new ItemStack(item(NS + ":watering_can")), unbreaking, false, failures);
        // Vanilla control: unchanged 1.20.1 behaviour.
        expectAnvil(helper, survival, new ItemStack(Items.DIAMOND_HOE), efficiency, true, failures);

        Player creative = PortGameTests.makeMockPlayer(helper, GameType.CREATIVE);
        creative.getAbilities().instabuild = true; // anvil applies any compatible enchantment in creative
        // 1.21.1 exclusive sets: Looting + Silk Touch compatible, Sharpness + Impaling not.
        expectAnvil(helper, creative, enchanted(item(NS + ":rusty_sword"), looting), silkTouch, true, failures);
        expectAnvil(helper, creative, enchanted(item(NS + ":rusty_sword"), sharpness), impaling, false, failures);
        // Vanilla control keeps the 1.20.1 class rule (LootBonusEnchantment excludes Silk Touch).
        expectAnvil(helper, creative, enchanted(Items.DIAMOND_SWORD, looting), silkTouch, false, failures);
        if (!failures.isEmpty()) helper.fail("anvil: " + failures);
        helper.succeed();
    }

    /** End-to-end {@code /enchant} on a StardewCraft item uses the 1.21.1 supported items. */
    @GameTest(templateNamespace = "stardewcraft_port_dump", template = "empty")
    public static void enchantCommandUses1211RulesForStardewItems(GameTestHelper helper) {
        MinecraftServer server = helper.getLevel().getServer();
        List<String> failures = new ArrayList<>();
        Object[][] cases = {
                {NS + ":hoe", "minecraft:efficiency", true},
                {NS + ":hoe", "minecraft:fortune", true},
                {NS + ":scythe", "minecraft:efficiency", false},
                {NS + ":fishing_rod", "minecraft:lure", false},
                {NS + ":rusty_sword", "minecraft:sharpness", true},
        };
        for (Object[] c : cases) {
            ArmorStand stand = helper.spawn(EntityType.ARMOR_STAND, new BlockPos(0, 1, 0));
            ItemStack stack = new ItemStack(item((String) c[0]));
            stand.setItemSlot(EquipmentSlot.MAINHAND, stack);
            server.getCommands().performPrefixedCommand(server.createCommandSourceStack().withSuppressedOutput(),
                    "enchant " + stand.getStringUUID() + " " + c[1] + " 1");
            boolean got = EnchantmentHelper.getEnchantments(stand.getMainHandItem()).containsKey(enchantment((String) c[1]));
            if (got != (Boolean) c[2]) failures.add(c[0] + " /enchant " + c[1] + " expected " + c[2]);
            stand.discard();
        }
        if (!failures.isEmpty()) helper.fail("/enchant: " + failures);
        helper.succeed();
    }
}
